package mysql.shopping;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 주문 테이블.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 주문 아이디. */
	private Integer oid;

	/** 주문일시. */
	private Date orderdate;

	/** totalPrice. */
	private Integer totalprice;

	/** 사용자. */
	private Users users;

	/** The set of 카트 테이블. */
	private Set<Cart> cartSet;

	/**
	 * Constructor.
	 */
	public Orders() {
		this.cartSet = new HashSet<Cart>();
	}

	/**
	 * Set the 주문 아이디.
	 * 
	 * @param oid
	 *            주문 아이디
	 */
	public void setOid(Integer oid) {
		this.oid = oid;
	}

	/**
	 * Get the 주문 아이디.
	 * 
	 * @return 주문 아이디
	 */
	public Integer getOid() {
		return this.oid;
	}

	/**
	 * Set the 주문일시.
	 * 
	 * @param orderdate
	 *            주문일시
	 */
	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	/**
	 * Get the 주문일시.
	 * 
	 * @return 주문일시
	 */
	public Date getOrderdate() {
		return this.orderdate;
	}

	/**
	 * Set the totalPrice.
	 * 
	 * @param totalprice
	 *            totalPrice
	 */
	public void setTotalprice(Integer totalprice) {
		this.totalprice = totalprice;
	}

	/**
	 * Get the totalPrice.
	 * 
	 * @return totalPrice
	 */
	public Integer getTotalprice() {
		return this.totalprice;
	}

	/**
	 * Set the 사용자.
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * Get the 사용자.
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * Set the set of the 카트 테이블.
	 * 
	 * @param cartSet
	 *            The set of 카트 테이블
	 */
	public void setCartSet(Set<Cart> cartSet) {
		this.cartSet = cartSet;
	}

	/**
	 * Add the 카트 테이블.
	 * 
	 * @param cart
	 *            카트 테이블
	 */
	public void addCart(Cart cart) {
		this.cartSet.add(cart);
	}

	/**
	 * Get the set of the 카트 테이블.
	 * 
	 * @return The set of 카트 테이블
	 */
	public Set<Cart> getCartSet() {
		return this.cartSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((oid == null) ? 0 : oid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (oid == null) {
			if (other.oid != null) {
				return false;
			}
		} else if (!oid.equals(other.oid)) {
			return false;
		}
		return true;
	}

}
