package mysql.bbs.erd;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 사용자.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자 아이디. */
	private String uid;

	/** 패스워드. */
	private String pwd;

	/** 사용자 이름. */
	private String uname;

	/** email. */
	private String email;

	/** 가입일자. */
	private Date regdate;

	/** The set of 게시판. */
	private Set<Board> boardSet;

	/** The set of 댓글. */
	private Set<Reply> replySet;

	/**
	 * Constructor.
	 */
	public Users() {
		this.boardSet = new HashSet<Board>();
		this.replySet = new HashSet<Reply>();
	}

	/**
	 * Set the 사용자 아이디.
	 * 
	 * @param uid
	 *            사용자 아이디
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * Get the 사용자 아이디.
	 * 
	 * @return 사용자 아이디
	 */
	public String getUid() {
		return this.uid;
	}

	/**
	 * Set the 패스워드.
	 * 
	 * @param pwd
	 *            패스워드
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * Get the 패스워드.
	 * 
	 * @return 패스워드
	 */
	public String getPwd() {
		return this.pwd;
	}

	/**
	 * Set the 사용자 이름.
	 * 
	 * @param uname
	 *            사용자 이름
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * Get the 사용자 이름.
	 * 
	 * @return 사용자 이름
	 */
	public String getUname() {
		return this.uname;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 가입일자.
	 * 
	 * @param regdate
	 *            가입일자
	 */
	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	/**
	 * Get the 가입일자.
	 * 
	 * @return 가입일자
	 */
	public Date getRegdate() {
		return this.regdate;
	}

	/**
	 * Set the set of the 게시판.
	 * 
	 * @param boardSet
	 *            The set of 게시판
	 */
	public void setBoardSet(Set<Board> boardSet) {
		this.boardSet = boardSet;
	}

	/**
	 * Add the 게시판.
	 * 
	 * @param board
	 *            게시판
	 */
	public void addBoard(Board board) {
		this.boardSet.add(board);
	}

	/**
	 * Get the set of the 게시판.
	 * 
	 * @return The set of 게시판
	 */
	public Set<Board> getBoardSet() {
		return this.boardSet;
	}

	/**
	 * Set the set of the 댓글.
	 * 
	 * @param replySet
	 *            The set of 댓글
	 */
	public void setReplySet(Set<Reply> replySet) {
		this.replySet = replySet;
	}

	/**
	 * Add the 댓글.
	 * 
	 * @param reply
	 *            댓글
	 */
	public void addReply(Reply reply) {
		this.replySet.add(reply);
	}

	/**
	 * Get the set of the 댓글.
	 * 
	 * @return The set of 댓글
	 */
	public Set<Reply> getReplySet() {
		return this.replySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uid == null) ? 0 : uid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (uid == null) {
			if (other.uid != null) {
				return false;
			}
		} else if (!uid.equals(other.uid)) {
			return false;
		}
		return true;
	}

}
